-- Contract 테이블에 만료 상태 추가
ALTER TABLE `contracts`
MODIFY COLUMN `status` ENUM(
  'PENDING_APPROVAL',
  'APPROVED',
  'REJECTED',
  'PAYMENT_COMPLETED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED_BY_GUEST',
  'CANCELLED_BY_HOST',
  'REFUNDED',
  'APPROVAL_EXPIRED',
  'PAYMENT_EXPIRED'
) NOT NULL DEFAULT 'PENDING_APPROVAL' COMMENT '계약 상태';
